class Autogenerated {
  String? message;
  Data? data;

  Autogenerated({this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  int? id;
  String? name;
  int? categoryId;
  String? category;
  String? categoryImage;
  int? propertyTypeId;
  String? propertyType;
  int? price;
  String? priceFormat;
  int? furnishedType;
  int? sallerType;
  int? propertyFor;
  int? ageOfProperty;
  int? maintenance;
  int? securityDeposit;
  int? brokerage;
  int? bhk;
  String? sqft;
  String? description;
  String? country;
  String? state;
  String? city;
  String? latitude;
  String? longitude;
  String? address;
  String? videoUrl;
  int? status;
  int? premiumProperty;
  String? propertyImage;
  List<String>? propertyGallary;
  List<PropertyGallaryArray>? propertyGallaryArray;
  String? createdAt;
  String? updatedAt;
  int? isFavourite;
  int? advertisementProperty;
  String? advertisementPropertyDate;

  Data(
      {this.id,
        this.name,
        this.categoryId,
        this.category,
        this.categoryImage,
        this.propertyTypeId,
        this.propertyType,
        this.price,
        this.priceFormat,
        this.furnishedType,
        this.sallerType,
        this.propertyFor,
        this.ageOfProperty,
        this.maintenance,
        this.securityDeposit,
        this.brokerage,
        this.bhk,
        this.sqft,
        this.description,
        this.country,
        this.state,
        this.city,
        this.latitude,
        this.longitude,
        this.address,
        this.videoUrl,
        this.status,
        this.premiumProperty,
        this.propertyImage,
        this.propertyGallary,
        this.propertyGallaryArray,
        this.createdAt,
        this.updatedAt,
        this.isFavourite,
        this.advertisementProperty,
        this.advertisementPropertyDate});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    categoryId = json['category_id'];
    category = json['category'];
    categoryImage = json['category_image'];
    propertyTypeId = json['property_type_id'];
    propertyType = json['property_type'];
    price = json['price'];
    priceFormat = json['price_format'];
    furnishedType = json['furnished_type'];
    sallerType = json['saller_type'];
    propertyFor = json['property_for'];
    ageOfProperty = json['age_of_property'];
    maintenance = json['maintenance'];
    securityDeposit = json['security_deposit'];
    brokerage = json['brokerage'];
    bhk = json['bhk'];
    sqft = json['sqft'];
    description = json['description'];
    country = json['country'];
    state = json['state'];
    city = json['city'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    address = json['address'];
    videoUrl = json['video_url'];
    status = json['status'];
    premiumProperty = json['premium_property'];
    propertyImage = json['property_image'];
    propertyGallary = json['property_gallary'].cast<String>();
    if (json['property_gallary_array'] != null) {
      propertyGallaryArray = <PropertyGallaryArray>[];
      json['property_gallary_array'].forEach((v) {
        propertyGallaryArray!.add(new PropertyGallaryArray.fromJson(v));
      });
    }
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    isFavourite = json['is_favourite'];
    advertisementProperty = json['advertisement_property'];
    advertisementPropertyDate = json['advertisement_property_date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['category_id'] = this.categoryId;
    data['category'] = this.category;
    data['category_image'] = this.categoryImage;
    data['property_type_id'] = this.propertyTypeId;
    data['property_type'] = this.propertyType;
    data['price'] = this.price;
    data['price_format'] = this.priceFormat;
    data['furnished_type'] = this.furnishedType;
    data['saller_type'] = this.sallerType;
    data['property_for'] = this.propertyFor;
    data['age_of_property'] = this.ageOfProperty;
    data['maintenance'] = this.maintenance;
    data['security_deposit'] = this.securityDeposit;
    data['brokerage'] = this.brokerage;
    data['bhk'] = this.bhk;
    data['sqft'] = this.sqft;
    data['description'] = this.description;
    data['country'] = this.country;
    data['state'] = this.state;
    data['city'] = this.city;
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['address'] = this.address;
    data['video_url'] = this.videoUrl;
    data['status'] = this.status;
    data['premium_property'] = this.premiumProperty;
    data['property_image'] = this.propertyImage;
    data['property_gallary'] = this.propertyGallary;
    if (this.propertyGallaryArray != null) {
      data['property_gallary_array'] =
          this.propertyGallaryArray!.map((v) => v.toJson()).toList();
    }
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['is_favourite'] = this.isFavourite;
    data['advertisement_property'] = this.advertisementProperty;
    data['advertisement_property_date'] = this.advertisementPropertyDate;
    return data;
  }
}

class PropertyGallaryArray {
  int? id;
  String? url;

  PropertyGallaryArray({this.id, this.url});

  PropertyGallaryArray.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['url'] = this.url;
    return data;
  }
}
